### ISSUE TITLE
Failed to install tl via npm install

### ISSUE THREAD

**Issue by mohsentaleb** [mojodna/tl#2]
With the following error:

> npm ERR! mapnik@3.1.3 install: `node-pre-gyp install --fallback-to-build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the mapnik@3.1.3 install script.
> npm ERR! This is most likely a problem with the mapnik package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-pre-gyp install --fallback-to-build
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls mapnik
> npm ERR! There is likely additional logging output above.
> npm ERR! System Windows_NT 6.1.7601
> npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "tl"
> npm ERR! cwd C:\Users\Mohsen
> npm ERR! node -v v0.10.35
> npm ERR! npm -v 1.4.28
> npm ERR! code ELIFECYCLE
> npm ERR! not ok code 0

**Comment by sethfitz** [comment]
Try installing a 32-bit `node.exe` per https://github.com/mapnik/node-mapnik/issues/343#issuecomment-61578164

**Comment by sethfitz** [comment]
I'm not familiar with the intricacies of installing Mapnik on Windows, so you'll probably have better luck here: https://github.com/mapnik/node-mapnik/issues

You can more directly replicate the problem using `npm install mapnik` in an empty directory.

**Comment by mohsentaleb** [comment]
I'm already on 32-bit node. My machine runs on Windows7 32-bit.

**Comment by sethfitz** [comment]
Tracking in https://github.com/mapnik/node-mapnik/issues/367
