### ISSUE TITLE
Raster files generated didn't load

### ISSUE THREAD

**Issue by aliir74** [mojodna/tl#27]
Hi all.
I used below command to generate some raster tiles but all png files are broken and didn't show anything.
```
~/node_modules/tl/bin/tl.js copy -z 7 -Z 9 -b "0.023293972 40.4104003077 3.6146087646 42.9542303723" mapbox:///mapbox.mapbox-streets-v4 file://./tiles
```

**Comment by sethfitz** [comment]
This isn't actually generating PNGs. [`tilelive-file`](https://github.com/mapbox/tilelive-file) creates files with `.png` as a default extension.

This command is just copying MVTs from Mapbox to a local filesystem. The `.png`s on the filesystem are MVTs.

To render rasters, you'll need to use `tilelive-tmstyle` to convert the MVTs into images according to a style you define.
