### ISSUE TITLE
Node 0.12.x and iojs compatibility

### ISSUE THREAD

**Issue by nirvine** [mojodna/tl#5]
From a newbie:
I have an error when I try to install - "cannot read property 'trim' of undefined"
![capture](https://cloud.githubusercontent.com/assets/4746171/7103603/aea35774-e0f2-11e4-8723-b445034a0ebc.JPG)

Can I fix this myself, or do I need help?

**Comment by sethfitz** [comment]
Try using Node 0.10.x. I haven't had a chance to try it with 0.12.

**Comment by sethfitz** [comment]
https://github.com/mojodna/tl/commit/b2b59ee6a2684b8e88db14dad115e388a9013c31 represents a first step for this.

https://github.com/mapbox/abaculus/pull/15 is needed in order for it to fully install on 0.12 and iojs.

**Comment by sethfitz** [comment]
Pending https://github.com/mapbox/abaculus/issues/17

**Comment by sethfitz** [comment]
Published as v0.4.0
